name: mpv AppImage2
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 16 1/7 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |
        sudo apt update
        sudo apt install libxpresent-dev libpulse-dev libxcb-shm0-dev libvpx-dev \
        liblua5.2-dev libxkbcommon-dev libxcb-xfixes0-dev equivs libavutil-dev \
        libavcodec-dev libswscale-dev python3-dev cython3 g++ nasm yasm git \
        libavfilter-dev libxmu-dev libxcb1-dev libdbus-1-dev libx11-dev \
        libxinerama-dev libxrandr-dev intltool libtool libwayland-dev \
        wayland-protocols devscripts libass-dev libx264-dev libxss-dev \
        libglib2.0-dev libpango1.0-dev binutils libxdg-basedir-dev libnotify-dev \
        libc++-dev libplacebo-dev libx265-dev ninja-build meson autotools-dev \
        autoconf automake make build-essential pkg-config desktop-file-utils zsync

        chmod a+x ./mpv-AppImage.sh && ./mpv-AppImage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mpv-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: mpv-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
